CREATE TABLE USER_INFO 
(
  USER_ID NUMBER(5) NOT NULL 
, USER_NAME VARCHAR2(20) 
, USER_EMAIL VARCHAR2(20) 
, CONSTRAINT USER_INFO_PK PRIMARY KEY 
  (
    USER_ID 
  )
  ENABLE 
);

COMMENT ON COLUMN USER_INFO.USER_ID IS '저장 된 순서';

COMMENT ON COLUMN USER_INFO.USER_NAME IS '유저 이름';

COMMENT ON COLUMN USER_INFO.USER_EMAIL IS '유저 이메일';
